In [43]:
import pandas as pd

In [44]:
import nltk
import underthesea
import numpy as np

In [45]:
filename = 'spam.csv'
df = pd.read_csv(filename,encoding = 'latin-1')
print(df.shape)
print(df.head(2))

(5572, 5)
    v1                                                 v2 Unnamed: 2  \
0  ham  Go until jurong point, crazy.. Available only ...        NaN   
1  ham                      Ok lar... Joking wif u oni...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  


In [46]:
data = df.values
print(data.shape)
lines = data[:,1]
labels = data[:,0]
print(lines[:5])
print(labels[:20])


(5572, 5)
['Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'
 'Ok lar... Joking wif u oni...'
 "Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's"
 'U dun say so early hor... U c already then say...'
 "Nah I don't think he goes to usf, he lives around here though"]
['ham' 'ham' 'spam' 'ham' 'ham' 'spam' 'ham' 'ham' 'spam' 'spam' 'ham'
 'spam' 'spam' 'ham' 'ham' 'spam' 'ham' 'ham' 'ham' 'spam']


In [47]:
sentences = [nltk.word_tokenize(sent) for sent in lines]
print(sentences[0])

['Go', 'until', 'jurong', 'point', ',', 'crazy', '..', 'Available', 'only', 'in', 'bugis', 'n', 'great', 'world', 'la', 'e', 'buffet', '...', 'Cine', 'there', 'got', 'amore', 'wat', '...']


In [48]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentences)

In [49]:
X = tokenizer.texts_to_matrix(sentences,mode='binary')
print(X)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 1. 0. ... 1. 1. 0.]
 [0. 0. 1. ... 0. 0. 1.]
 [0. 1. 0. ... 0. 0. 0.]]


In [50]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, labels, 
                                            test_size=0.2, random_state=0)
print(X_train)
print(y_train)
print(X_test)
print(y_test)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]]
['ham' 'ham' 'ham' ... 'ham' 'ham' 'ham']
[[0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 ...
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]]
['ham' 'ham' 'ham' ... 'ham' 'ham' 'ham']


In [51]:
# Mô hình Multinomial
from sklearn.naive_bayes import MultinomialNB 
from sklearn.metrics import classification_report
model_NB = MultinomialNB()
model_NB = model_NB.fit(X_train,y_train)
y_pred = model_NB.predict(X_test)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         ham       0.99      0.99      0.99       949
        spam       0.93      0.92      0.92       166

    accuracy                           0.98      1115
   macro avg       0.96      0.95      0.96      1115
weighted avg       0.98      0.98      0.98      1115



In [52]:
input_sent = 'Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 20010'
tokens = nltk.word_tokenize(input_sent)
print(tokens)
X_input = tokenizer.texts_to_matrix([tokens],mode='binary')
print(X_input)

['Free', 'entry', 'in', '2', 'a', 'wkly', 'comp', 'to', 'win', 'FA', 'Cup', 'final', 'tkts', '21st', 'May', '20010']
[[0. 0. 0. ... 0. 0. 0.]]


In [53]:
y_pred = model_NB.predict(X_input)
print(y_pred)

['spam']


In [54]:
# Mô hình Gausian
from sklearn.naive_bayes import GaussianNB
model_GNB = GaussianNB()
model_GNB = model_GNB.fit(X_train,y_train)
y_pred = model_GNB.predict(X_test)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         ham       0.98      0.90      0.94       949
        spam       0.62      0.89      0.73       166

    accuracy                           0.90      1115
   macro avg       0.80      0.90      0.84      1115
weighted avg       0.93      0.90      0.91      1115



In [55]:
input_sent = 'Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 20010'
tokens = nltk.word_tokenize(input_sent)
print(tokens)
X_input = tokenizer.texts_to_matrix([tokens],mode='binary')
print(X_input)

['Free', 'entry', 'in', '2', 'a', 'wkly', 'comp', 'to', 'win', 'FA', 'Cup', 'final', 'tkts', '21st', 'May', '20010']
[[0. 0. 0. ... 0. 0. 0.]]


In [56]:
y_pred = model_GNB.predict(X_input)
print(y_pred)

['spam']


In [57]:
# Mô hình Bernoulli
from sklearn.naive_bayes import BernoulliNB
model_BNB = BernoulliNB()
model_BNB = model_BNB.fit(X_train,y_train)
y_pred = model_BNB.predict(X_test)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         ham       0.97      1.00      0.98       949
        spam       0.98      0.81      0.89       166

    accuracy                           0.97      1115
   macro avg       0.97      0.91      0.94      1115
weighted avg       0.97      0.97      0.97      1115



In [58]:
input_sent = 'Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 20010'
tokens = nltk.word_tokenize(input_sent)
print(tokens)
X_input = tokenizer.texts_to_matrix([tokens],mode='binary')
print(X_input)

['Free', 'entry', 'in', '2', 'a', 'wkly', 'comp', 'to', 'win', 'FA', 'Cup', 'final', 'tkts', '21st', 'May', '20010']
[[0. 0. 0. ... 0. 0. 0.]]


In [59]:
y_pred = model_BNB.predict(X_input)
print(y_pred)

['spam']
